name = "justImageViewer"
product-name = "JustImageViewer"
identifier = "com.rosenkim.justImageViewer"
version = "0.2.0"
out-dir = "./dist"
binaries-dir = "./target/release"
before-packaging-command = "cargo build --release"

icons = [
  "assets/icon.icns",
  "assets/app.ico",
  "assets/icon.png"
]

[[binaries]]
path = "justImageViewer"
main = true