name = "image-viewer"
product-name = "Vibe-Image-Viewer"
identifier = "com.packager.vibe-image-viewer"
version = "0.2.0"
out-dir = "./dist"
binaries-dir = "./target/release"
before-packaging-command = "cargo build --release"

icons = [
  "assets/icon.icns",
  "assets/app.ico",
  "assets/icon.png"
]

[[binaries]]
path = "vibe-image-viewer"
main = true